name: Docker Image CI

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
    paths:
      - ".github/**"
      - "Dockerfile"
      - "**.ts"

jobs:
  call-docker-build:
    uses: ethdevops/workflows/.github/workflows/basic-docker-build.yaml@main
    secrets:
      docker_registry_user: ${{ secrets.DOCKER_REGISTRY_USER }}
      docker_registry_password: ${{ secrets.DOCKER_REGISTRY_SECRET }}
