name: Docker Image CI

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ghcr.io/nordeck/jitsi-keycloak-adapter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build jitsi-keycloak-adapter
      run: |
        docker build -t jitsi-keycloak-adapter

    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push jitsi-keycloak-adapter
      run: |
        docker tag jitsi-keycloak-adapter:latest ${{ env.DOCKER_IMAGE }}:latest
        docker push ${{ env.DOCKER_IMAGE }}:latest
